<?php
// $Id: audio_feeds.module,v 1.6 2008/09/25 23:18:08 drewish Exp $
/**
 * @file
 * This module provides XSPF, M3U, and PLS feeds for a list of audio files.
 */

/**
 * Implementation of hook_help().
 */
function audio_feeds_help($section, $arg) {
  switch ($section) {
    case 'admin/help#audio_feeds':
      return t('This module creates XSPF, M3U, and PLS audio feeds.');
  }
}

/**
 * Implementation of hook_form_alter().
 */
function audio_feeds_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  switch ($form_id) {
    case 'node_type_form':
      if (isset($form['identity']['type']) && module_exists('audio_attach')) {
        $type = $form['#node_type']->type;
        $form['workflow']['audio_feeds_attach'] = array(
          '#type' => 'radios',
          '#title' => t('Audio Feeds'),
          '#default_value' => variable_get('audio_feeds_attach_'. $type, 0),
          '#options' => array(t('Disabled'), t('Enabled')),
          '#description' => t('Should users be allowed to create XSPF, M3U, and PLS feeds of attached audio files?'),
        );
      }
      break;
  }
}

/**
 * Implementation of hook_link().
 */
function audio_feeds_link($type, $node = NULL, $teaser = FALSE) {
  global $base_url;
  global $user;
  $links = array();

  if (variable_get('audio_feeds_attach_'. $node->type, 0) && count($node->audio_attach) > 0) {
    // Add audio playlist feed links
    $feed_links = variable_get('audio_feeds_feed_links', array('m3u', 'pls', 'xspf', 'popup'));
    foreach ($feed_links as $key => $type) {
      switch ((string)$type) {
        case 'm3u':
          $links['audio_feeds_m3u_link'] = array(
             'title' => t('M3U'),
             'href' => "node/$node->nid/m3u",
             'attributes' => array('title' => t('Stream M3U feed')),
          );
          break;
        case 'pls':
          $links['audio_feeds_pls_link'] = array(
             'title' => t('PLS'),
             'href' => "node/$node->nid/pls",
             'attributes' => array('title' => t('Stream PLS feed')),
          );
          break;
        case 'xspf':
          $links['audio_feeds_xspf_link'] = array(
             'title' => t('XSPF'),
             'href' => "node/$node->nid/xspf",
             'attributes' => array('title' => t('Shareable XSPF feed')),
          );
          break;
        default:
          break;
      }
    }
  }

  return $links;
}

/**
 * Implementation of hook_menu().
 */
function audio_feeds_menu() {
  // FIXME: This snippet isn't preserved by this new menu code:
  // if (variable_get('audio_feeds_attach_'. $node->type, 0)) {
  $items = array();

  $items['node/%node/xspf'] = array(
    'title' => 'XSPF',
    'page callback' => 'audio_feeds_xspf',
    'page arguments' => array(1),
    'file' => 'audio_feeds.feeds.inc',
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/m3u'] = array(
    'title' => 'M3U',
    'page callback' => 'audio_feeds_m3u',
    'page arguments' => array(1),
    'file' => 'audio_feeds.feeds.inc',
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/pls'] = array(
    'title' => 'PLS',
    'page callback' => 'audio_feeds_pls',
    'page arguments' => array(1),
    'file' => 'audio_feeds.feeds.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
