<?php
// $Id: file_views.module,v 1.12 2008/09/23 11:05:55 miglius Exp $

/**
 * @file
 * Integrates file operations with the Views module.
 */

//////////////////////////////////////////////////////////////////////////////

define('FILE_VIEWS_TITLE_LENGTH_SHORT', 18);

//////////////////////////////////////////////////////////////////////////////
// Views API hooks

/**
 * Implementation of hook_views_api().
 */
function file_views_views_api() {
  return array(
    'api' => 2,
  );
}

